name: capture-semgrep

on:
  pull_request:

permissions:
  contents: read

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Capture resolved auto config
        run: curl --location --fail --silent --show-error https://semgrep.dev/c/auto -o semgrep-auto.yml
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: semgrep-auto-config
          path: semgrep-auto.yml
          if-no-files-found: error
