name: release

on:
  push:
    branches: ['release/*']

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
      security-events: write
      id-token: write
      attestations: write
      packages: write
      issues: write
      actions: read
      pull-requests: write
      pages: write
    uses: ./.github/workflows/publish.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
